spring:
  profiles:
    active: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: petshowmail12@gmail.com
    password: nffmjchahjnrhxjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
