spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petshow?reconnect=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  app-url: "http://localhost:4200"
  jpa:
     show-sql: false
     properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE