spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com/heroku_8d6dc28ad3aca5d
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ba7e334648dc49
    password: 103060ba
  app-url: "http://localhost:4200"
  jpa:
     show-sql: false
     properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE