spring:
  profiles: localdb
  datasource:
    url: jdbc:mysql://mysql:3306/petshow-local?reconnect=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
