spring:
  datasource:
    #url: jdbc:h2:file:~/Documentos/projeto-integrado/database/db_temp
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:C:\Users\user\Desktop\Peshow\db_temp_PetShow
    driverClassName: org.h2.Driver
    username: sa
    password: password
  app-url: "http://localhost:4200"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
