spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  app-url: "https://petshow-frontend.herokuapp.com/"