spring:
  profiles:
    active: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${env.PETSHOW_MAIL}
    password: ${env.PETSHOW_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
