name: generate-and-send-coverage-report
on:
  push:
    branches:
      - master
jobs:
  run-gradle-task-and-send-to-codacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReport
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{secrets.CODACY_PROJECT_TOKEN}}