name: gradle-build-n-push
on:
  push:
    branches:
      - development
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - uses: actions/checkout@master
      - name: Create local changes
        run: |
          git status
          git add src/main/resources/jacoco/jacocoTestReport.xml
      - name: Commit files
        run: |
          git config --local user.email "guilhermeguis@outlook.com"
          git config --local user.name "Guilherme Souza"
          git commit -m "Push automático do relatório de coverage após build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: development